version: '3'  

services:
  book-api: 
    build: .
    ports:
      - "8080:8080"  
    environment:
      - MONGO_URI=mongodb://mongodb:27017/NodeJS-CRUD
      - APP_PORT=8080
    volumes:
      - ./:/app 
    links:
      - mongodb
    depends_on:
      - mongodb 
    networks:
      - local 

  mongodb:  
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - local 
    volumes:
      - mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
    networks:
      - local 

networks:
  local:
    driver: bridge

volumes:
  mongodb: {}
    


